### ISSUE TITLE
Eclector probably needs PEEK-CHAR

### ISSUE THREAD

**Issue by scymtym** [robert-strandh/Eclector#11]
```
<beach> Just an observation:
<beach> I think Eclector must have an implementation of PEEK-CHAR, because for
	some combination of arguments, it checks whether the character is a
	whitespace character. 
<beach> So the native PEEK-CHAR can not be used, because it would not consult
	the Eclector readtable for character syntax.
<drmeister> Check with Bike - we ran into this already.
<beach> Also, currently, Eclector doesn't use PEEK-CHAR simply because I
	completely forgot about its existence.  But some parts of the reader
	could be faster when PEEK-CHAR is used.
<scymtym> beach: sounds right. could you make an issue for this? ideally
	  including a code snippet demonstrating the problem
```

**Comment by robert-strandh** [comment]
Eclector definitely needs PEEK-CHAR.  Here is a code snippet:

 (setf (eclector.readtable:syntax-type eclector.reader:*readtable* #\tab) :single-escape)

(with-input-from-string (stream (coerce '(#\tab #\x) 'string)) (eclector.reader:read stream))

(with-input-from-string (stream (coerce '(#\tab #\x) 'string)) (peek-char t stream))

Reading from that string returns |x| as expected.  PEEK-CHAR on the other hand still
considers the TAB character to be whitespace, so it returns the character x.
